
server:
  port: 8080

eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes: 
        - id: Cinebox
          uri: lb://CINEBOX
          predicates:
            -path=/cinebox/**
